### ISSUE TITLE
[copyq] memory leak

### ISSUE THREAD

**Issue by thiagoa** [albertlauncher/python#135]
Yesterday I noticed that the Albert process in my machine was taking up 1.1 GB of memory. Then I noticed a correlation with CopyQ, even though Albert takes up a lot of memory by default when it launches. I couldn't find a problem with the Python script, so maybe it has to do with the way Albert manages the entries generated by the plugin.

#### Steps to reproduce

- Set CopyQ entry limit to 50 and fill it up
- Enable the Python CopyQ plugin
- Trigger CopyQ in Albert with "cq"
- Each time you trigger it, it will eat up ~10 MB of memory (at least on my machine)

#### Expected behaviour

Memory should go down and stabilize, but it doesn't seem so.

**Comment by ManuelSchneid3r** [comment]
@BarrensZeppelin iirc you are taking care of CQ. Did you encouter this issue recently or can I consider this issue obsolete?

**Comment by BarrensZeppelin** [comment]
> @BarrensZeppelin iirc you are taking care of CQ. Did you encouter this issue recently or can I consider this issue obsolete?

I'll try to see if I can reproduce it.

**Comment by ManuelSchneid3r** [comment]
I close this one. Reopen if the issue appears agai

**Comment by BarrensZeppelin** [comment]
I did try to reproduce it but couldn't. :+1:
