### ISSUE TITLE
[googletrans] Not able to use Google Translate due to an import error

### ISSUE THREAD

**Issue by DenverCoder1** [albertlauncher/python#148]
This seems to be because the plugin module is named `googletrans` which conflicts with the module name of the Python library.

```
Failed loading 'googletrans': ImportError: cannot import name 'Translator' from partially initialized module 'googletrans' (most likely due to a circular import) (/home/jonah/.local/share/albert/python/plugins/googletrans/__init__.py)

At:
  /home/jonah/.local/share/albert/python/plugins/googletrans/__init__.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/jonah/.local/share/albert/python/plugins/googletrans/__init__.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
```

**Comment by ManuelSchneid3r** [comment]
This problem will often occur. That's why the plugins are imported in the "albert." namespace by the python plugin. I appreciate your ambitions, but please join the chats and discuss rather systematic ideas briefly before you start coding. On my side it is uncomfortable to reject already done work.

**Comment by DenverCoder1** [comment]
If there's a better alternative, I don't mind if you close the PR. This was only like a 10-second fix in any case.

I'm not sure I understand what you're suggesting though, isn't it always the case that you can't name a module the same as a package module you are trying to import because it causes circular imports as shown in the error above? The plugin crashes without renaming the folder and works if it is renamed.

**Comment by ManuelSchneid3r** [comment]
It is usually. But [see this](https://github.com/albertlauncher/plugins/blob/master/python/src/plugin.cpp#L441-L442). The plugin `__name__` becomes `albert.googletrans`.

**Comment by DenverCoder1** [comment]
Thanks for the explanation, it does appear to work with version 0.18.11.
