### ISSUE TITLE
how to do not use Triggers in python plugins ?

### ISSUE THREAD

**Issue by talengu** [albertlauncher/python#170]
#### Description
can we want use no trigger to triger "Window Switcher" action? in python

![image](https://github.com/albertlauncher/python/assets/10290923/24ef8436-e9f5-40d1-a886-9e68a194fe24)

do not use "w" as trigger ?

![image](https://github.com/albertlauncher/python/assets/10290923/d9fa1cce-73e3-46db-aefb-065e5a82a3a9)

**Comment by ManuelSchneid3r** [comment]
@talengu hey send a PR for the plugin. unfortunately this is not possible yet. if we would allow this, we'd have to allow multiple plugins to have a empty trigger, but triggered queryhandlers are intended to run exclusively. they have the ability to add items asynchronously. this does not work with multiple handlers such that it makes sense for the user.

but this gives me an idea: future plan is to have a tab in the settings to control the handlers which should be in the global search. maybe we could add a checkbox to allow dedicaded handlers to handle the empty query. this will work for global handlers only though. the window switcher is a triggerQueryHandler afaik.
