### ISSUE TITLE
Problems with logging

### ISSUE THREAD

**Issue by AdamPS** [albertlauncher/python#181]
#### Description
With the new v0.22 I have some problems with logging in my python plug-ins.

albert.pyi includes a `warning` function, see https://github.com/albertlauncher/python/blob/master/albert.pyi#L330

1) If I try to log a warning in my plug-in I get a warning

> NameError: name 'warning' is not defined

2) If I try to import warning my plug-in fails to load

> Failed loading plugin 'bookmarks': ImportError: cannot import name 'warning' from 'albert' (unknown location)

3) Code `warn()` **does** work

4) I can't import warn, or info

5) Code `debug()` doesn't generate any warning, however I don't see a log even with `albert -d`

#### Expected behavior
Write a warning to the log

#### Steps to reproduce
1) Add code
`warning('Danger')`

2) Add code
`from albert import warning`

#### Source
http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/

#### Debug output

Already posted in the description

**Comment by ManuelSchneid3r** [comment]
0.22.1 fixes this issue

**Comment by ManuelSchneid3r** [comment]
> 4\. I can't import warn, or info

the logging functions are attached to the module at runtime, because they have to be redirected through a prepared QLoggingCategory such that the python modules play nicely with the logging filter you can set with the `-l` commandline option (and `-d` and `-q`).

**Comment by ManuelSchneid3r** [comment]
> 5\. Code `debug()` doesn't generate any warning, however I don't see a log even with `albert -d`

thats interesting and probably a bug, let me test it.
