### ISSUE TITLE
urlopen fails with https

### ISSUE THREAD

**Issue by lcrippa** [albertlauncher/python#7]
When executing a python module like google translate or wikipedia, an error rises on request.urlopen(req): 

`[GoogleTranslate] URLError: <urlopen error unknown url type: https>.`

Changing the address with an http one the extension works fine. However, python3 is correctly installed on the system and running the same command in a python shell (python 3.6.3, debian sid) gives no error.

**Comment by benedictdudel** [comment]
Can confirm the issue with the following code sample:

```python
>>> import requests
>>> r = requests.get('https://github.com/timeline.json')
>>> r.json()
[{u'repository': {u'open_issues': 0, u'url': 'https://github.com/...
```

**Comment by ManuelSchneid3r** [comment]
OS?

**Comment by lcrippa** [comment]
Operating system: 4.12.0-2-amd64 #1 SMP Debian 4.12.13-1 (2017-09-19) x86_64 GNU/Linux
Desktop environment: Gnome Shell
Qt version: 5.9.1
Albert version: dev

**Comment by ManuelSchneid3r** [comment]
Please post the output of 
```
python
>>> import socket
>>> hasattr(socket, "ssl")
```

**Comment by ManuelSchneid3r** [comment]
Okay no thats bullshit

**Comment by ManuelSchneid3r** [comment]
Can you import ssl?

**Comment by lcrippa** [comment]
yes, I tried both things and it works fine (also the commands in the script work fine on python shell)

**Comment by ManuelSchneid3r** [comment]
Hmm I cant reproduce this issue. Also I am not that familar with python internals. I'd appreciate if you could do some research and post your findings here.

**Comment by lcrippa** [comment]
So here's what I found up to now:
adding
`import ssl`
to the python wikipedia script, I find the following error:
`17:00:42 [WARN] [Wikipedia] ImportError: /usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_OSError`.

I checked and the said library exists. I found a bug that might be related here: 
[(https://stackoverflow.com/questions/11842920/undefined-symbol-pyexc-importerror-when-embedding-python-in-c)]
then I tried to add the mentioned flag
`set(CMAKE_SHARED_LINKER_FLAGS "/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so")`
to the cmake file, but I obtained a lot of errors when trying to make:
`/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyLong_FromLong'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyArg_NoPositional'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyModule_Create2'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyByteArray_Type'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyType_IsSubtype'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_GC_Track'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyEval_RestoreThread'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyExc_MemoryError'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_NoMemory'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_FromString'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyBytes_FromString'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_WriteUnraisable'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_GetBuffer'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_FSConverter'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyBytes_Resize'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyBytes_AsString'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyObject_GC_New'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_Clear'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyCallable_Check'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyArg_ParseStack_SizeT'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyBuffer_Release'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_GC_Del'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyExc_TypeError'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_SetObject'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyType_Ready'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyArg_Parse_SizeT'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyList_AsTuple'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_NewExceptionWithDoc'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyList_Size'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_Decode'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyDict_GetItem'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_AsEncodedString'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_FromEncodedObject'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyTime_AsMilliseconds'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyTuple_New'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_CallFunctionObjArgs'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_AsASCIIString'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_Occurred'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyWeakref_NewRef'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyBytes_FromStringAndSize'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyDict_SetItem'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyExc_ValueError'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_FromFormat'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_Py_FalseStruct'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyDict_SetItemString'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyExc_OverflowError'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyTime_GetMonotonicClock'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyModule_GetDict'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_BadArgument'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyWeakref_GetObject'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_DecodeFSDefault'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyGILState_Ensure'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_SetString'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_CallObject'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyBuffer_IsContiguous'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_SetFromErrnoWithFilenameObject'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyList_Append'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyMem_Free'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyUnicode_FromStringAndSize'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyExc_IOError'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyObject_New'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_Py_NoneStruct'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyArg_NoKeywords'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyDict_New'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_CheckSignals'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyArg_ParseTuple_SizeT'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyGILState_Release'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyModule_AddObject'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_Py_NotImplementedStruct'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyExc_RuntimeWarning'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyErr_BadInternalCall'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_Free'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyBool_FromLong'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyLong_AsLong'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_Py_TrueStruct'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_SetFromErrno'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyType_FromSpec'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_WarnFormat'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyEval_SaveThread'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_GC_UnTrack'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyCapsule_Import'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_Py_BuildValue_SizeT'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_Py_fopen_obj'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyModule_AddIntConstant'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyMem_Malloc'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyList_New'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `_PyObject_SetAttrId'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyObject_Str'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyErr_Format'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyExc_OSError'
/usr/lib/python3.6/lib-dynload/_ssl.cpython-36m-x86_64-linux-gnu.so: undefined reference to `PyLong_FromUnsignedLong'
`

Not sure if this is relevant though

**Comment by lcrippa** [comment]
(I seem to have closed the issue. Did not mean to, sorry)

**Comment by ManuelSchneid3r** [comment]
Not a problem anymore?

**Comment by lcrippa** [comment]
I think commit 33bde7b fixed it

**Comment by ManuelSchneid3r** [comment]
That was a hell to track down.

**Comment by lcrippa** [comment]
haha yeah, I can only imagine... thanks a lot!
